# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Philipp M. Lersch
email: p.m.lersch@hu-berlin.de
description: >- # this means to ignore newlines until "baseurl:"
  Website of Philipp M. Lersch who is a sociologist at Humboldt-Universität zu Berlin and DIW Berlin/SOEP.
twitter_username: PMLersch
github_username: pmlersch
minimal_mistakes_skin: dirt
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
 # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
 # - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : " "
  avatar : "/assets/images/lersch_portrait.jpg"
  bio    : "Sociologist at Humboldt-Universität zu Berlin and DIW Berlin."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pmlersch"
    - label: "OSF"
      icon: "ai ai-osf-square"
      url: "https://osf.io/y29xd/"      
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square"
      url: "http://scholar.google.com/citations?user=602KhhQAAAAJ&hl=eng"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "http://orcid.org/0000-0003-3863-8301"  
    - label: "Institutional website"
      icon: "fa fa-link"
      url: "https://www.sowi.hu-berlin.de/en/lehrbereiche-en/sozpolsoz/team/1691159"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
